# Generated by Django 2.2.3 on 2019-07-05 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='date_complete',
            new_name='date_completed',
        ),
    ]
